version: '3'

services:
  netbox:
    image: netboxcommunity/netbox:latest
    container_name: netbox
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASS=netboxpassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      - POSTGRES_DB=netbox
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD=netboxpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis

volumes:
  postgres_data:
